services:
  - type: web
    name: al-noir
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    preDeployCommand: "python manage.py migrate --noinput && python manage.py ensure_superuser"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.console.EmailBackend"
      - key: DEFAULT_FROM_EMAIL
        value: "noreply@alnoir.ro"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: "3.13.14"
