# Generated by Django 5.2.15 on 2026-07-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_id_alter_menuitem_id'),
        ('reservations', '0002_table_reservation_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-reservation_date', '-reservation_time'], 'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['number'], 'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
        migrations.RemoveField(
            model_name='table',
            name='is_active',
        ),
        migrations.AddField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('inactive', 'Inactive')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guests',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='selected_items',
            field=models.ManyToManyField(blank=True, related_name='reservations', to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='special_request',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.PositiveSmallIntegerField(choices=[(2, '2 Persons'), (4, '4 Persons'), (6, '6 Persons'), (10, '10 Persons')]),
        ),
    ]
