# Generated by Django 5.2.15 on 2026-07-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_advance_amount_reservation_advance_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='reservation',
            name='promo_code',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
