# Generated by Django 5.2.15 on 2026-07-14 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitem_is_loyalty_reward_alter_category_id_and_more'),
        ('reservations', '0005_reservation_discount_amount_reservation_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='promo_free_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_reservations', to='menu.menuitem'),
        ),
    ]
