# Generated by Django 5.2.15 on 2026-08-05 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitem_is_loyalty_reward_alter_category_id_and_more'),
        ('reservations', '0006_reservation_promo_free_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('table', 'reservation_date', 'reservation_time'), name='unique_active_table_slot'),
        ),
    ]
