# Generated by Django 5.2.15 on 2026-08-05 17:48

import reservations.models
from django.db import migrations, models


def backfill_access_tokens(apps, schema_editor):
    Reservation = apps.get_model('reservations', 'Reservation')
    for reservation in Reservation.objects.all():
        reservation.access_token = reservations.models.generate_access_token()
        reservation.save(update_fields=['access_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_reservation_unique_active_table_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='access_token',
            field=models.CharField(default='', editable=False, max_length=43, blank=True),
        ),
        migrations.RunPython(backfill_access_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='reservation',
            name='access_token',
            field=models.CharField(default=reservations.models.generate_access_token, editable=False, max_length=43, unique=True),
        ),
    ]
