# Generated by Django 5.2.15 on 2026-09-10 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0006_favorite_rating"),
        ("reservations", "0009_alter_reservation_guests"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("guests__gte", 1)), name="reservation_guests_gte_1"
            ),
        ),
    ]
