# Generated by Django 5.2.15 on 2026-07-14 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_sale_customer_loyaltyaccount_loyaltyredemption_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('guests', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('waiting', 'În așteptare'), ('notified', 'Notificat'), ('converted', 'Rezervare creată'), ('cancelled', 'Anulat')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('reservation_date', 'reservation_time', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ceo', 'CEO'), ('manager', 'Manager'), ('waiter', 'Ospătar'), ('kitchen', 'Bucătărie / Bar')], default='waiter', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('clocked_in_at', models.DateTimeField(blank=True, null=True)),
                ('clocked_out_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='operations.staffprofile')),
            ],
            options={
                'ordering': ('-starts_at',),
            },
        ),
    ]
