# Generated by Django 5.2.15 on 2026-08-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_waitlistentry_staffprofile_staffshift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='0 means unlimited'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('supplier', 'Supplier'), ('salary', 'Salary'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage discount'), ('fixed', 'Fixed discount'), ('free_item', 'Free item')], default='percent', max_length=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('online', 'Online')], default='card', max_length=10),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('ceo', 'CEO'), ('manager', 'Manager'), ('waiter', 'Waiter'), ('kitchen', 'Kitchen / Bar')], default='waiter', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('waste', 'Waste/Expired'), ('adjustment', 'Adjustment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('notified', 'Notified'), ('converted', 'Reservation created'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
    ]
