# Generated by Django 5.2.15 on 2026-08-13 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0005_alter_event_capacity_alter_expense_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="waitlistentry",
            name="guests",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
