# Generated by Django 5.2.15 on 2026-08-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0006_alter_ticket_quantity_alter_waitlistentry_guests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("purchase", "Purchase"),
                    ("sale", "Sale"),
                    ("waste", "Waste / Expired"),
                    ("adjustment", "Adjustment"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="waitlistentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("notified", "Notified"),
                    ("converted", "Converted"),
                    ("cancelled", "Cancelled"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
    ]
