# Generated by Django 5.2.15 on 2026-09-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0007_alter_stockmovement_movement_type_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="stockitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)),
                name="stockitem_quantity_gte_0",
            ),
        ),
    ]
