# Generated by Django 5.2.15 on 2026-09-10 18:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0008_stockitem_stockitem_quantity_gte_0"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="expense_date",
            field=models.DateField(
                db_index=True, default=django.utils.timezone.localdate
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
