# Generated by Django 5.2.15 on 2026-07-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_id_alter_menuitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_loyalty_reward',
            field=models.BooleanField(default=False, help_text='Poate fi oferit ca desert gratuit prin programul de loialitate.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
