# Generated by Django 5.2.15 on 2026-08-05 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitem_is_loyalty_reward_alter_category_id_and_more'),
        ('operations', '0004_waitlistentry_staffprofile_staffshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stock_item',
            field=models.ForeignKey(blank=True, help_text='Dacă e setat, stocul acestui produs scade automat la fiecare vânzare.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='operations.stockitem'),
        ),
    ]
