# Generated by Django 5.2.15 on 2026-08-05 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitem_stock_item'),
        ('operations', '0005_alter_event_capacity_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='is_loyalty_reward',
            field=models.BooleanField(default=False, help_text='Can be offered as a free dessert through the loyalty program.'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='stock_item',
            field=models.ForeignKey(blank=True, help_text="If set, this item's stock decreases automatically with every sale.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='operations.stockitem'),
        ),
    ]
